<DetailScreen>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'vertical'
            Label:
                text: "You are now connected"
                font_size: 32
            ImageAnimation:
        BoxLayout:
            size_hint: (3, 1)
            Button:
                text: "Disconnect"
                font_size: 24
                on_press: root.disconnect()







